name: 🎵 SoundCloud → Dropbox

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      SOUNDCLOUD_CLIENT_ID: ${{ secrets.SOUNDCLOUD_CLIENT_ID }}
      USERNAME: '1339565397'

    steps:
      # Step 1: Checkout with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete git history

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run main script
      - name: Run downloader
        run: python main.py

      # Step 5: Update and push track records
      - name: Update and push track records
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Pull latest changes and reset
          git fetch origin
          git reset --hard origin/main
          
          # Add files and commit if changes exist
          git add downloaded_tracks.json failed_tracks.json
          git diff --cached --quiet || git commit -m "Auto-update track records"
          
          # Push changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Using your custom TOKEN secret
