name: 🎵 SoundCloud → Dropbox

on:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      SOUNDCLOUD_CLIENT_ID: ${{ secrets.SOUNDCLOUD_CLIENT_ID }}
      USERNAME: '1339565397'

    steps:
      # Étape 1: Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour les opérations git

      # Étape 2: Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3: Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4: Exécution du script principal
      - name: Run downloader
        run: python main.py

      # Étape 5: Mise à jour des fichiers JSON et push
      - name: Commit and push changes
        run: |
          # Configuration git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Synchronisation avec le dépôt distant
          git fetch origin main
          git reset --hard origin/main
          
          # Ajout des fichiers et commit
          git add downloaded_tracks.json failed_tracks.json
          git commit -m "Mise à jour automatique des pistes" || echo "Aucun changement à commiter"
          
          # Push des modifications
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
