name: 🎵 SoundCloud → Dropbox

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'   # Runs every five minutes

jobs:
  download:
    runs-on: ubuntu-latest

    env:
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      SOUNDCLOUD_CLIENT_ID: ${{ secrets.SOUNDCLOUD_CLIENT_ID }}
      USERNAME: '1339565397'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run downloader
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add downloaded_tracks.json failed_tracks.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update track records" && git push)
