name: 🎵 SoundCloud → Dropbox

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      SOUNDCLOUD_CLIENT_ID: ${{ secrets.SOUNDCLOUD_CLIENT_ID }}
      USERNAME: '1339565397'

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt
      
      - run: python main.py
